# problem conf
n_objectives: 3
n_variables: 5
problem: "vehicle crash worthiness"

# LEMOO conf
fitness_fun: "PointMethodASF"
use_darwin: true
use_ml: true
ml_probe: null
ml_threshold: null
darwin_probe: null
darwin_threshold: null

# EA conf
pop_size: 200
populatin_init_design: "LHSDesign"
ea_iterations_per_cycle: 1

# ML conf
h_split: 0.2
l_split: 0.2
instantation_factor: 10
generation_lookback: 0
ancestral_recall: 0
unique_only: true
ml_iterations_per_cycle: 1

# ML model conf
ml_model_name: "SkopedRuleClassifier"
ml_precision_min: 0.1
ml_n_estimators: 30
ml_max_features: null
ml_max_depth: null
ml_bootstrap: true
ml_bootstrap_features: true
